# Generated by Django 5.1.4 on 2024-12-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_price_product_unit_price_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
    ]
